### ISSUE TITLE
Error with TAE js'

### ISSUE THREAD

**Issue by smendez-hi** [SIMPATICOProject/IFE#1]
Hi.
I was seeing this error in the console: `taeUI.getInstance is not a function`. The problem is  that `tae-ui-popup.js` declares a variable with the same name as `tae-ui.js`, and because of the order of this 2 scripts in `index_demo.html` it isn't working.

**Comment by xPret** [comment]
There exist two TAEs clients: the "tae-ui.js & tae-core.js" client[DEUSTO/Galicia], which enriches the text below each paragraph, and the "tae-ui-popus.js & tae-core-popup.js" one [FBK/Trento], which shows a popup. The way that makes most sense to us is to choose one of them. However, in order to enable both ways in the same webpage the tae-core-popup.js variable is renamed to taeUIPopup.
